In [2]:
import pandas as pd
import jieba
print("everything is working!")

everything is working!

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/jieba/_compat.py:18: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

In [2]:
import pandas as pd
import random

random.seed(42)

case_types = ["criminal", "civil", "administrative"]
provinces  = ["Beijing", "Guangdong", "Sichuan", "Xinjiang", "Shanghai"]
demo_texts = [
    "被告人认罪态度良好，系初犯，依法从轻处罚，判处有期徒刑一年，缓期执行。",
    "被告人犯罪情节严重，依法严厉打击，维护社会秩序，判处有期徒刑十年。",
    "证据不足，无法认定被告人有罪，依法宣告无罪。",
    "被告人违法行为恶劣，社会危害性大，从严惩处，判处有期徒刑五年。",
    "被告人认罪悔罪，积极赔偿损失，酌情从轻，判处拘役三个月。",
]

df = pd.DataFrame({
    "text":        [random.choice(demo_texts) for _ in range(50)],
    "case_type":   [random.choice(case_types)  for _ in range(50)],
    "province":    [random.choice(provinces)   for _ in range(50)],
    "year":        [random.randint(2015, 2023) for _ in range(50)],
    "court_level": [random.choice(["district", "intermediate", "high"]) for _ in range(50)],
})

print(f"Created {len(df)} demo verdicts")
print(df.head())

Created 50 demo verdicts
                                  text       case_type   province  year  \
0  被告人认罪态度良好，系初犯，依法从轻处罚，判处有期徒刑一年，缓期执行。           civil   Xinjiang  2022
1  被告人认罪态度良好，系初犯，依法从轻处罚，判处有期徒刑一年，缓期执行。  administrative    Sichuan  2015
2               证据不足，无法认定被告人有罪，依法宣告无罪。  administrative    Beijing  2019
3    被告人犯罪情节严重，依法严厉打击，维护社会秩序，判处有期徒刑十年。           civil  Guangdong  2023
4    被告人犯罪情节严重，依法严厉打击，维护社会秩序，判处有期徒刑十年。  administrative   Shanghai  2017

    court_level
0      district
1  intermediate
2      district
3          high
4          high

In [3]:
print("Verdicts by case type:")
print(df["case_type"].value_counts())

print("\nVerdicts by province:")
print(df["province"].value_counts())

print("\nYear range:")
print(f"Earliest: {df['year'].min()}, Latest: {df['year'].max()}")

Verdicts by case type:
case_type
administrative    18
criminal          17
civil             15
Name: count, dtype: int64

Verdicts by province:
province
Xinjiang     12
Shanghai     11
Guangdong    10
Sichuan       9
Beijing       8
Name: count, dtype: int64

Year range:
Earliest: 2015, Latest: 2023

In [7]:
df_real = pd.read_csv("data/ThirdPartyCases_RandomSample500.csv")

print(f"Loaded {len(df_real)} real cases")
print(df_real.columns.tolist())
df_real.head()

Loaded 500 real cases
['Case.ID', 'code', 'court', 'hightransparency']

   Case.ID  code         court  hightransparency
0  1000796     1  郑州市管城回族区人民法院                 0
1  1003878     0       孟州市人民法院                 0
2  1004540     1       虞城县人民法院                 0
3  1009881     1       新蔡县人民法院                 0
4  1009889     1     河南省高级人民法院                 0

In [8]:
print("Number of cases:", len(df_real))
print("\nColumn names:")
print(df_real.columns.tolist())
print("\nFirst few rows:")
df_real.head()

Number of cases: 500

Column names:
['Case.ID', 'code', 'court', 'hightransparency']

First few rows:

   Case.ID  code         court  hightransparency
0  1000796     1  郑州市管城回族区人民法院                 0
1  1003878     0       孟州市人民法院                 0
2  1004540     1       虞城县人民法院                 0
3  1009881     1       新蔡县人民法院                 0
4  1009889     1     河南省高级人民法院                 0

In [9]:
from datasets import load_dataset

# Load just a small slice (first 500 cases) instead of the full 2.6 million
cail = load_dataset("china-ai-law-challenge/cail2018", split="exercise_contest_train", streaming=True)

# Pull the first 500 examples into a list
sample_cases = []
for i, example in enumerate(cail):
    if i >= 500:
        break
    sample_cases.append(example)

print(f"Loaded {len(sample_cases)} real cases with verdict text")
print(sample_cases[0])

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loaded 500 real cases with verdict text
{'fact': '昌宁县人民检察院指控，2014年4月19日下午16时许，被告人段某驾拖车经过鸡飞乡澡塘街子，时逢堵车，段某将车停在“冰凉一夏”冷饮店门口，被害人王某的侄子王2某示意段某靠边未果，后上前敲打车门让段某离开，段某遂驾车离开，但对此心生怨愤。同年4月21日22时许，被告人段某酒后与其妻子王1某一起准备回家，走到鸡飞乡澡塘街富达通讯手机店门口时停下，段某进入手机店内对被害人王某进行吼骂，紧接着从手机店出来拿得一个石头又冲进手机店内朝王某头部打去，致王某右额部粉碎性骨折、右眼眶骨骨折。经鉴定，被害人王某此次损伤程度为轻伤一级。', 'relevant_articles': [234], 'accusation': ['故意伤害'], 'punish_of_money': 0.0, 'criminals': ['段某'], 'death_penalty': False, 'imprisonment': 12.0, 'life_imprisonment': False}

In [4]:
import plotly.express as px

fig = px.bar(
    df["province"].value_counts().reset_index(),
    x="province",
    y="count",
    title="Number of Verdicts by Province",
    color="province",
)
fig.show()

In [10]:
import pandas as pd

# Convert the list of cases into a proper dataframe
df_real = pd.DataFrame(sample_cases)
print("Columns:", df_real.columns.tolist())
print("\nNumber of cases:", len(df_real))
df_real.head()

Columns: ['fact', 'relevant_articles', 'accusation', 'punish_of_money', 'criminals', 'death_penalty', 'imprisonment', 'life_imprisonment']

Number of cases: 500

,fact,relevant_articles,accusation,punish_of_money,criminals,death_penalty,imprisonment,life_imprisonment
0,昌宁县人民检察院指控，2014年4月19日下午16时许，被告人段某驾拖车经过鸡飞乡澡塘街子，...,[234],[故意伤害],0.0,[段某],False,12.0,False
1,"公诉机关指控,2015年11月10日晚9时许，被告人李某的妹妹李某某与被害人华某某在桦川县悦...",[234],[故意伤害],0.0,[李某],False,10.0,False
2,贵州省平坝县人民检察院指控：2014年4月9日下午，被告人王某丁与其堂哥王4某（另案处理）假...,"[292, 234]",[故意伤害],0.0,[王某丁],False,42.0,False
3,经审理查明：2014年5月6日14时许，被告人叶某某驾车途径赤壁市赵李桥镇胜利街涵洞时，被在...,[234],[故意伤害],0.0,[叶某某],False,12.0,False
4,安阳县人民检察院指控：2014年4月27日上午11时许，宋某甲在安阳县吕村镇翟奇务村被告人梁...,[234],[故意伤害],0.0,[梁某甲],False,12.0,False